### PR TITLE
CA-208166: DockerMachine(golang clients) cannot connect XenServer host with ssl-legacy=false

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Phus Lu phus.lu@citrix.com

### CODE REVIEW

**Comment by Zhengchai** [comment]
Looks good. Could we merge it to resolve CA-208166 at the moment?

**Comment by jonludlam** [comment]
Has the patch been accepted upstream?

**Comment by ghost** [comment]
Not yet in golang master/release branches.

A existing issue raised at https://github.com/golang/go/issues/9894
But golang only added TLS_RSA_WITH_AES_128_GCM_SHA256 and **ignored** TLS_RSA_WITH_AES_128_CBC_SHA256 to resolve this issue. :disappointed: 

Our XenServer with ssl-legacy=false, always strict cipher suites to TLS_RSA_WITH_AES_128_CBC_SHA256 in server side.
Therefore, at this moment, DockerMachine(golang clients) could not establish TLS connections to XenServer.
So we submit this PR to resolve this problem.

**Comment by Zhengchai** [comment]
Based on the discussion with Phus Lu, to patch Golang compiler is the only/best way to enable the XenServer Docker Machine Driver to work with XenServer at the moment, given that XenServer has choose the specific Cipher. Otherwise the XenServer Docker Machine Driver will not work withXenServer with SSL.

So merge this ticket to resolve CA-208166, please ping me/push back me if any objections. Thanks

**Pull request merged**
